DECLARE
  V_DESCRICAO VARCHAR2(79);
  V_JOB       VARCHAR2(30);
BEGIN

  FOR X IN 1 .. 2000  LOOP
  
    V_DESCRICAO := 'ATIMO' || X;
  
    INSERT INTO G3E_JOB_TAB
      (G3E_IDENTIFIER,
       G3E_DESCRIPTION,
       G3E_OWNER,
       G3E_STATUS,
       G3E_CREATION,
       G3E_POSTED,
       G3E_CLOSED,
       G3E_ADDJOBATTR,
       G3E_ID,
       WR_STATE_CODE,
       SUBMITTED_DATE,
       G3E_STATUS_CODE,
       G3E_FIELDUSER,
       CD_SEQ,
       TS_EXTWR,
       CD_CREWHQ,
       FG_DESIGN_BY_TOOL,
       FG_MULTI_DSGN_CMPLT,
       DT_IN_SERVICE,
       CD_ZONE,
       ADDITIONALINFO,
       G3E_PROCESSINGSTATUS,
       G3E_JOBCLASS,
       WORK_REQUEST,
       VERSION,
       VERSION_NEXT,
       GIS_JOB_STATUS,
       DESIGN_DESCRIPTION,
       ASSIGNED_TO,
       REGION,
       DISTRICT,
       JOB_TYPE,
       JOB_CODE,
       ELECTRICAL_ACCOUNT,
       WR_ADDRESS,
       CONTACT_NM,
       CONTACT_TELE,
       DT_REQUIRED,
       FG_LOCKED_DOWN,
       DT_COMPLETE,
       CONTACT_ADDR,
       CD_JOB_MODE,
       ID_OPER_RESP_EST,
       ID_OPER_RESP_ASB,
       JOB_STATE,
       WORK_ORDER_ID,
       G3E_POSTFLAG,
       VSN_VR,
       UF,
       LOCALIDADE,
       SIGLA_ESTACAO,
       ESTACAO_DESTINO,
       LOCALIDADE_DESTINO)
    VALUES
      (G3E_JOB_IDENTIFIER.NEXTVAL,
       V_DESCRICAO,
       'CR018691',
       NULL,
       SYSDATE,
       NULL,
       NULL,
       NULL,
       NULL,
       NULL,
       NULL,
       NULL,
       NULL,
       1,
       SYSDATE,
       NULL,
       NULL,
       NULL,
       NULL,
       NULL,
       NULL,
       0,
       0,
       1,
       1,
       NULL,
       'NEW',
       NULL,
       NULL,
       'HSV',
       NULL,
       'PRO_A',
       NULL,
       NULL,
       NULL,
       NULL,
       NULL,
       NULL,
       NULL,
       NULL,
       NULL,
       NULL,
       NULL,
       NULL,
       'PRP',
       NULL,
       NULL,
       NULL,
       'RS',
       NULL,
       NULL,
       NULL,
       NULL);
    COMMIT;
  
    SELECT G3E_IDENTIFIER
      INTO V_JOB
      FROM G3E_JOB_TAB
     WHERE G3E_DESCRIPTION = V_DESCRICAO;
  
    LTT_ADMIN.CreateJob(V_JOB, FALSE);
  
  END LOOP;
END;
