SET echo ON;

SPOOL FSPLICE_LOCAL_INSTALACAO.log;

--Cria a Tabela REF
CREATE TABLE REF_LOCAL_INSTALACAO
 (
  LOCAL_INSTALACAO                   VARCHAR2(30) NOT NULL,
  CONSTRAINT local_instalacao_pk PRIMARY KEY(LOCAL_INSTALACAO)
 );
CREATE OR REPLACE PUBLIC SYNONYM REF_LOCAL_INSTALACAO FOR GPROD.REF_LOCAL_INSTALACAO;
GRANT ALL ON REF_LOCAL_INSTALACAO to EVERYONE;

--Popula Tabela REF
INSERT INTO REF_LOCAL_INSTALACAO VALUES ('Aérea');
INSERT INTO REF_LOCAL_INSTALACAO VALUES ('Subterrânea');
COMMIT;

--INSERIR NA G3E_PICKLIST
insert into g3e_picklist (G3E_PNO, G3E_USERNAME, G3E_TABLE, G3E_KEYFIELD, G3E_VALUEFIELD, G3E_VALIDATION, G3E_FILTER, G3E_ADDITIONALFIELDS, G3E_EDITDATE, G3E_LOCALECOMMENT, G3E_ORDERBYKEY, G3E_PUBLISH, G3E_ADDITIONALPUBLISHFIELDS)
values (11805, 'REF_LOCAL_INSTALACAO.LOCAL_INSTALACAO', 'REF_LOCAL_INSTALACAO', 'LOCAL_INSTALACAO', 'LOCAL_INSTALACAO', 'G3ERestricted', null, null, SYSDATE, null, null, 1, null);
commit;

-- Adiciona colunas na tabela base
ALTER TABLE B$GC_FSPLICE ADD LOCAL_INSTALACAO VARCHAR2(100);


-- Este bloco abaixo recria views, triggers e outros objetos atrelado à tabela
UPDATE G3E_GENERALPARAMETER SET G3E_VALUE='1' WHERE G3E_NAME='IgnoreSubsettingForLTT';
COMMIT;

EXEC G3E_GENERALPARAMETER_PKG.CREATEOPTIMIZEDTABLE;
COMMIT;

BEGIN
  CREATE_VIEWS.CREATE_LTT_VIEW('B$GC_FSPLICE');
  CONSTRAINT_TRANSFER.GETPRIMARYCONSTRAINT('B$GC_FSPLICE');
  CONSTRAINT_TRANSFER.DROPUNIQUECONSTRAINT('B$GC_FSPLICE');
  CONSTRAINT_TRANSFER.DROPUNIQUEINDEX('B$GC_FSPLICE');
  CREATE_TRIGGERS.CREATE_LTT_TRIGGER('B$GC_FSPLICE');
  --GDOTRIGGERS.CREATE_GDOTRIGGERS('B$GC_FSPLICE');
END;
/

UPDATE G3E_GENERALPARAMETER SET G3E_VALUE='0' WHERE G3E_NAME='IgnoreSubsettingForLTT';
COMMIT;

EXEC G3E_GENERALPARAMETER_PKG.CREATEOPTIMIZEDTABLE;
COMMIT;
--------------------------------------------------------------INSERIR O PNO ABAIXO----------------------------------------------------

-- Insere as novas colunas na tabela de metadados G3E_ATTRIBUTE
INSERT INTO G3E_ATTRIBUTE 
VALUES (1180109,11801,NULL,'LOCAL_INSTALACAO','Local de Instalação',NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,11805,0,0,10,NULL,NULL,0,SYSDATE,NULL,NULL,NULL,0,0,1,NULL,NULL,NULL,0,NULL,1,'EVERYONE',NULL,NULL,NULL);
COMMIT;

-- Insere as novas colunas na tabela de metadados G3E_TABATTRIBUTE
INSERT INTO G3E_TABATTRIBUTE (G3E_TANO,G3E_ANO,G3E_ORDINAL,G3E_READONLY,G3E_REFRESH,G3E_DTNO,G3E_EDITDATE,G3E_TRIGGERPOPULATE,G3E_USEFILTERTOTRANSLATEKEY) VALUES (118010112,1180109,3,0,1,1180101,SYSDATE,0,0);
INSERT INTO G3E_TABATTRIBUTE (G3E_TANO,G3E_ANO,G3E_ORDINAL,G3E_READONLY,G3E_REFRESH,G3E_DTNO,G3E_EDITDATE,G3E_TRIGGERPOPULATE,G3E_USEFILTERTOTRANSLATEKEY) VALUES (118010212,1180109,3,0,1,1180102,SYSDATE,0,0);
INSERT INTO G3E_TABATTRIBUTE (G3E_TANO,G3E_ANO,G3E_ORDINAL,G3E_READONLY,G3E_REFRESH,G3E_DTNO,G3E_EDITDATE,G3E_TRIGGERPOPULATE,G3E_USEFILTERTOTRANSLATEKEY) VALUES (118010312,1180109,3,1,1,1180103,SYSDATE,0,0);
COMMIT;

execute MG3ElanguageSubTableUtils.SynchronizeSubTables;
COMMIT;
execute MG3EOTCreateOptimizedTables;
COMMIT;
execute MG3ECreateOptableViews;
COMMIT;

execute ComponentQuery.Generate;
commit;
execute ComponentViewQuery.Generate;
commit;
execute gc_compileinvalidobjects;
commit;


SPOOL OFF;