
create user CEMIG identified by CEMIG account unlock  default tablespace GENEDATOS profile default;
grant administrator to CEMIG;
grant advance to CEMIG;
grant connect to CEMIG;
grant dba to CEMIG;
grant everyone to CEMIG;
grant exp_full_database to CEMIG;
grant finance to CEMIG;
grant imp_full_database to CEMIG;
grant resource to CEMIG;
grant supervisor to CEMIG;
grant connect to CEMIG;
grant create procedure to CEMIG;
grant create public synonym to CEMIG;
grant create role to CEMIG;
grant create sequence to CEMIG;
grant create session to CEMIG;
grant create table to CEMIG;
grant create trigger to CEMIG;
grant create type to CEMIG;
grant create view to CEMIG; 
grant any role to CEMIG;
grant resource to CEMIG;
grant select any table to CEMIG;
grant drop public synonym to CEMIG;
grant unlimited tablespace to CEMIG;
grant alter any procedure to CEMIG;
grant imp_full_database to CEMIG;
grant exp_full_database to CEMIG;
grant select on dba_roles to CEMIG;
grant select on dba_role_privs to CEMIG;
grant select on v_$session to CEMIG;
grant select on v_$transaction to CEMIG;
grant execute on dbms_lock to CEMIG;
